scheduler:
  baseUrl: ${BASE_URL}
  name: node
  options:
    concurrency:
      default: 5

quarkus:
  package:
    type: fast-jar

  http:
    cors: true
    port: 80

  oidc:
    enabled: true
    auth-server-url: https://keycloak.com/auth/realms/quarkus
    client-id: client
    credentials:
      secret: secret
    application-type: SERVICE
    tls:
      verification: none

  infinispan-client:
    server-list: ${ISPN_NODE}
    use-schema-registration: false
    use-auth: true
    auth-username: ${ISPN_USER}
    auth-password: ${ISPN_PASS}

  swagger-ui:
    always-include: true

  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
    category:
      "org.jboss.pnc":
        level: DEBUG
      "com.arjuna.ats.jta":
        # Set to WARN if you want to see all the exceptions
        level: ERROR
      "io.smallrye.faulttolerance.core":
        level: TRACE

  vertx:
    max-event-loop-execute-time: 10s

"%test":
   scheduler:
     baseUrl: http://localhost:8081
   quarkus:
     oidc:
       enabled: false
     transaction-manager:
       default-transaction-timeout: 10m
     http:
       port: 8081
     infinispan-client:
       client-intelligence: BASIC
       server-list: localhost:11222
       use-schema-registration: true
       use-auth: true
       auth-username: user
       auth-password: a1234

"%dev":
   scheduler:
     baseUrl: http://localhost:8181

   quarkus:
     transaction-manager:
       default-transaction-timeout: 10m
     http:
       port: 8181
     infinispan-client:
       server-list: localhost:11222
       use-schema-registration: true
       use-auth: true
       auth-username: user
       auth-password: a1234

     log:
       category:
         "org.jboss.pnc":
           level: TRACE
