scheduler:
  baseUrl: ${BASE_URL}
  name: node
  options:
    task-configuration:
      clean: true
    concurrency:
      default: 5
    internal-retry-policy:
      delay: 100
      jitter: 80
      max-retries: 15
      abort-on:
        - javax.validation.ConstraintViolationException
        - org.jboss.pnc.rex.common.exceptions.TaskMissingException
        - org.jboss.pnc.rex.common.exceptions.BadRequestException
        - org.jboss.pnc.rex.common.exceptions.TaskConflictException
        - org.jboss.pnc.rex.common.exceptions.CircularDependencyException
        - org.jboss.pnc.rex.common.exceptions.ConstraintConflictException
    http-configuration:
      idle-timeout: 300000 # 5 minutes
      follow-redirects: true
      request-retry-policy:
        backoff:
          min-delay: 0
          max-delay: 0
          jitter-factor: 0.5
        max-retries: 20
        expire-in: 0
      425-backoff-policy:
        backoff:
          min-delay: 200
          max-delay: 6000 # 1 minute
          jitter-factor: 0.5
        max-retries: 0
        expire-in: 600000 # 10minutes

quarkus:
  application:
    name: rex

  opentelemetry:
    enabled: true
    tracer:
      enabled: true
      # reflect sampling on collector
      resource-attributes: "sampler_ratio=0.05,service.name=rex"
      sampler:
        ratio: 0.05
      exporter:
        otlp:
          # Send telemetry data to an opentelemetry-collector
          #endpoint: http://localhost:4317

  package:
    type: fast-jar

  http:
    cors: true
    port: 80

  oidc:
    enabled: true
    auth-server-url: https://keycloak.com/auth/realms/quarkus
    client-id: client
    credentials:
      secret: secret
    application-type: SERVICE
    tls:
      verification: none
  oidc-client:
    enabled: true
    auth-server-url: https://keycloak.com/auth/realms/quarkus
    client-id: client
    credentials:
      secret: secret

  infinispan-client:
#    hosts: ${ISPN_NODE}
    use-schema-registration: false
    use-auth: true
    username: ${ISPN_USER}
    password: ${ISPN_PASS}
    near-cache-max-entries: 100

  swagger-ui:
    always-include: true

  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
    category:
      "org.jboss.pnc":
        level: DEBUG
      "com.arjuna.ats.jta":
        # Set to WARN if you want to see all the exceptions
        level: ERROR
    min-level: TRACE

  vertx:
    max-event-loop-execute-time: 10s

org:
  jboss:
    pnc:
      rex:
        core:
          delegates:
            TolerantQueueManager/poke/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
            TolerantQueueManager/poke/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
            TolerantQueueManager/poke/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
            TolerantQueueManager/poke/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
            TolerantQueueManager/decreaseRunningCounter/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
            TolerantQueueManager/decreaseRunningCounter/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
            TolerantQueueManager/decreaseRunningCounter/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
            TolerantQueueManager/decreaseRunningCounter/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
            TolerantQueueManager/setMaximumConcurrency/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
            TolerantQueueManager/setMaximumConcurrency/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
            TolerantQueueManager/setMaximumConcurrency/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
            TolerantQueueManager/setMaximumConcurrency/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
        rest:
          InternalEndpointImpl/finish/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
          InternalEndpointImpl/finish/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
          InternalEndpointImpl/finish/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
          InternalEndpointImpl/finish/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
          InternalEndpointImpl/succeed/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
          InternalEndpointImpl/succeed/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
          InternalEndpointImpl/succeed/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
          InternalEndpointImpl/succeed/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
          InternalEndpointImpl/fail/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
          InternalEndpointImpl/fail/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
          InternalEndpointImpl/fail/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
          InternalEndpointImpl/fail/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
          InternalEndpointImpl/setConcurrent/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
          InternalEndpointImpl/setConcurrent/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
          InternalEndpointImpl/setConcurrent/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
          InternalEndpointImpl/setConcurrent/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
          TaskEndpointImpl/start/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
          TaskEndpointImpl/start/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
          TaskEndpointImpl/start/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
          TaskEndpointImpl/start/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}
          TaskEndpointImpl/cancel/Retry/maxRetries: ${scheduler.options.internal-retry-policy.max-retries}
          TaskEndpointImpl/cancel/Retry/delay: ${scheduler.options.internal-retry-policy.delay}
          TaskEndpointImpl/cancel/Retry/jitter: ${scheduler.options.internal-retry-policy.jitter}
          TaskEndpointImpl/cancel/Retry/abortOn: ${scheduler.options.internal-retry-policy.abort-on}



"%test":
  scheduler:
    baseUrl: http://localhost:8081
    options:
      http-configuration:
        425-backoff-policy:
          backoff:
            min-delay: 10
            max-delay: 10
          expire-in: 5000
  quarkus:
    log:
      category:
        "org.testcontainers":
          level: DEBUG
      min-level: TRACE
    oidc:
      enabled: false
      auth-server-url: ""
    oidc-client:
      enabled: false
    transaction-manager:
      default-transaction-timeout: 10m
    http:
      port: 8081
    opentelemetry:
      enabled: false
      tracer:
        enabled: false
    infinispan-client:
      client-intelligence: BASIC
      use-schema-registration: true
      use-auth: true
      username: admin
      password: password
      cache:
        "rex-counter":
          configuration-uri: "counter-configuration.xml"
          near-cache-mode: disabled
          near-cache-max-entries: -1
        "rex-tasks":
          configuration-uri: "task-configuration.xml"
          near-cache-mode: invalidated
          near-cache-max-entries: 100
        "rex-constraints":
          configuration-uri: "constraints-configuration.xml"
          near-cache-mode: invalidated
          near-cache-max-entries: 100
      devservices:
#        image-name: "infinispan/server:13.0.5.Final-2"
        image-name: "quay.io/infinispan/server:14.0.2.Final"

"%dev":
  scheduler:
    baseUrl: http://localhost:8181
  disable:
    authorization: true
  quarkus:
    oidc:
      enabled: false
      auth-server-url: ""
    transaction-manager:
      default-transaction-timeout: 10m
    opentelemetry:
      enabled: false
      tracer:
        enabled: false
    http:
      port: 8181
    infinispan-client:
      client-intelligence: BASIC
      use-schema-registration: true
      use-auth: true
      username: admin
      password: password
      cache:
        "rex-counter":
          configuration-uri: "counter-configuration.xml"
          near-cache-mode: disabled
          near-cache-max-entries: -1
        "rex-tasks":
          configuration-uri: "task-configuration.xml"
          near-cache-mode: invalidated
          near-cache-max-entries: 100
        "rex-constraints":
          configuration-uri: "constraints-configuration.xml"
          near-cache-mode: invalidated
          near-cache-max-entries: 100
      devservices:
        #        image-name: "infinispan/server:13.0.5.Final-2"
        image-name: "quay.io/infinispan/server:14.0.2.Final"
    log:
      category:
        "org.jboss.pnc":
          level: TRACE
        "io.quarkus.infinispan":
          level: TRACE
        "io.opentelemetry":
          level: INFO
      min-level: FINEST
